//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.01 at 01:50:23 PM CET 
//


package com.base.engine.core.formats.ogre.mesh;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textures",
    "faces",
    "geometry",
    "boneassignments"
})
@XmlRootElement(name = "submesh")
public class Submesh {

    @XmlAttribute(name = "material", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String material;
    @XmlAttribute(name = "usesharedvertices")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String usesharedvertices;
    @XmlAttribute(name = "use32bitindexes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String use32Bitindexes;
    @XmlAttribute(name = "operationtype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String operationtype;
    protected Textures textures;
    @XmlElement(required = true)
    protected Faces faces;
    protected Geometry geometry;
    protected Boneassignments boneassignments;

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the usesharedvertices property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsesharedvertices() {
        if (usesharedvertices == null) {
            return "true";
        } else {
            return usesharedvertices;
        }
    }

    /**
     * Sets the value of the usesharedvertices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsesharedvertices(String value) {
        this.usesharedvertices = value;
    }

    /**
     * Gets the value of the use32Bitindexes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUse32Bitindexes() {
        if (use32Bitindexes == null) {
            return "false";
        } else {
            return use32Bitindexes;
        }
    }

    /**
     * Sets the value of the use32Bitindexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUse32Bitindexes(String value) {
        this.use32Bitindexes = value;
    }

    /**
     * Gets the value of the operationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationtype() {
        if (operationtype == null) {
            return "triangle_list";
        } else {
            return operationtype;
        }
    }

    /**
     * Sets the value of the operationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationtype(String value) {
        this.operationtype = value;
    }

    /**
     * Gets the value of the textures property.
     * 
     * @return
     *     possible object is
     *     {@link Textures }
     *     
     */
    public Textures getTextures() {
        return textures;
    }

    /**
     * Sets the value of the textures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Textures }
     *     
     */
    public void setTextures(Textures value) {
        this.textures = value;
    }

    /**
     * Gets the value of the faces property.
     * 
     * @return
     *     possible object is
     *     {@link Faces }
     *     
     */
    public Faces getFaces() {
        return faces;
    }

    /**
     * Sets the value of the faces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Faces }
     *     
     */
    public void setFaces(Faces value) {
        this.faces = value;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * @return
     *     possible object is
     *     {@link Geometry }
     *     
     */
    public Geometry getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geometry }
     *     
     */
    public void setGeometry(Geometry value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the boneassignments property.
     * 
     * @return
     *     possible object is
     *     {@link Boneassignments }
     *     
     */
    public Boneassignments getBoneassignments() {
        return boneassignments;
    }

    /**
     * Sets the value of the boneassignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boneassignments }
     *     
     */
    public void setBoneassignments(Boneassignments value) {
        this.boneassignments = value;
    }

}
