//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.01 at 01:50:23 PM CET 
//


package com.base.engine.core.formats.ogre.mesh;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vertex"
})
@XmlRootElement(name = "vertexbuffer")
public class Vertexbuffer {

    @XmlAttribute(name = "positions")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String positions;
    @XmlAttribute(name = "normals")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String normals;
    @XmlAttribute(name = "colours_diffuse")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String coloursDiffuse;
    @XmlAttribute(name = "colours_specular")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String coloursSpecular;
    @XmlAttribute(name = "texture_coords")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoords;
    @XmlAttribute(name = "texture_coord_dimensions_0")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions0;
    @XmlAttribute(name = "texture_coord_dimensions_1")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions1;
    @XmlAttribute(name = "texture_coord_dimensions_2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions2;
    @XmlAttribute(name = "texture_coord_dimensions_3")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions3;
    @XmlAttribute(name = "texture_coord_dimensions_4")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions4;
    @XmlAttribute(name = "texture_coord_dimensions_5")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions5;
    @XmlAttribute(name = "texture_coord_dimensions_6")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions6;
    @XmlAttribute(name = "texture_coord_dimensions_7")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textureCoordDimensions7;
    @XmlAttribute(name = "tangents")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tangents;
    @XmlAttribute(name = "tangent_dimensions")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tangentDimensions;
    @XmlAttribute(name = "binormals")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String binormals;
    @XmlElement(required = true)
    protected List<Vertex> vertex;

    /**
     * Gets the value of the positions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositions() {
        if (positions == null) {
            return "false";
        } else {
            return positions;
        }
    }

    /**
     * Sets the value of the positions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositions(String value) {
        this.positions = value;
    }

    /**
     * Gets the value of the normals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormals() {
        if (normals == null) {
            return "false";
        } else {
            return normals;
        }
    }

    /**
     * Sets the value of the normals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormals(String value) {
        this.normals = value;
    }

    /**
     * Gets the value of the coloursDiffuse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColoursDiffuse() {
        if (coloursDiffuse == null) {
            return "false";
        } else {
            return coloursDiffuse;
        }
    }

    /**
     * Sets the value of the coloursDiffuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColoursDiffuse(String value) {
        this.coloursDiffuse = value;
    }

    /**
     * Gets the value of the coloursSpecular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColoursSpecular() {
        if (coloursSpecular == null) {
            return "false";
        } else {
            return coloursSpecular;
        }
    }

    /**
     * Sets the value of the coloursSpecular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColoursSpecular(String value) {
        this.coloursSpecular = value;
    }

    /**
     * Gets the value of the textureCoords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoords() {
        if (textureCoords == null) {
            return "0";
        } else {
            return textureCoords;
        }
    }

    /**
     * Sets the value of the textureCoords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoords(String value) {
        this.textureCoords = value;
    }

    /**
     * Gets the value of the textureCoordDimensions0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions0() {
        if (textureCoordDimensions0 == null) {
            return "2";
        } else {
            return textureCoordDimensions0;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions0(String value) {
        this.textureCoordDimensions0 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions1() {
        if (textureCoordDimensions1 == null) {
            return "2";
        } else {
            return textureCoordDimensions1;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions1(String value) {
        this.textureCoordDimensions1 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions2() {
        if (textureCoordDimensions2 == null) {
            return "2";
        } else {
            return textureCoordDimensions2;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions2(String value) {
        this.textureCoordDimensions2 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions3() {
        if (textureCoordDimensions3 == null) {
            return "2";
        } else {
            return textureCoordDimensions3;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions3(String value) {
        this.textureCoordDimensions3 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions4() {
        if (textureCoordDimensions4 == null) {
            return "2";
        } else {
            return textureCoordDimensions4;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions4(String value) {
        this.textureCoordDimensions4 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions5() {
        if (textureCoordDimensions5 == null) {
            return "2";
        } else {
            return textureCoordDimensions5;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions5(String value) {
        this.textureCoordDimensions5 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions6() {
        if (textureCoordDimensions6 == null) {
            return "2";
        } else {
            return textureCoordDimensions6;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions6(String value) {
        this.textureCoordDimensions6 = value;
    }

    /**
     * Gets the value of the textureCoordDimensions7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextureCoordDimensions7() {
        if (textureCoordDimensions7 == null) {
            return "2";
        } else {
            return textureCoordDimensions7;
        }
    }

    /**
     * Sets the value of the textureCoordDimensions7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextureCoordDimensions7(String value) {
        this.textureCoordDimensions7 = value;
    }

    /**
     * Gets the value of the tangents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTangents() {
        if (tangents == null) {
            return "false";
        } else {
            return tangents;
        }
    }

    /**
     * Sets the value of the tangents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTangents(String value) {
        this.tangents = value;
    }

    /**
     * Gets the value of the tangentDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTangentDimensions() {
        if (tangentDimensions == null) {
            return "3";
        } else {
            return tangentDimensions;
        }
    }

    /**
     * Sets the value of the tangentDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTangentDimensions(String value) {
        this.tangentDimensions = value;
    }

    /**
     * Gets the value of the binormals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinormals() {
        if (binormals == null) {
            return "false";
        } else {
            return binormals;
        }
    }

    /**
     * Sets the value of the binormals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinormals(String value) {
        this.binormals = value;
    }

    /**
     * Gets the value of the vertex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vertex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVertex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vertice }
     * 
     * 
     */
    public List<Vertex> getVertex() {
        if (vertex == null) {
            vertex = new ArrayList<Vertex>();
        }
        return this.vertex;
    }

}
