//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.01 at 01:50:23 PM CET 
//


package com.base.engine.core.formats.ogre.mesh;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "vertexboneassignment")
public class Vertexboneassignment {

    @XmlAttribute(name = "vertexindex", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vertexindex;
    @XmlAttribute(name = "boneindex", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String boneindex;
    @XmlAttribute(name = "weight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String weight;

    /**
     * Gets the value of the vertexindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVertexindex() {
        return vertexindex;
    }

    /**
     * Sets the value of the vertexindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVertexindex(String value) {
        this.vertexindex = value;
    }

    /**
     * Gets the value of the boneindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoneindex() {
        return boneindex;
    }

    /**
     * Sets the value of the boneindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoneindex(String value) {
        this.boneindex = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        if (weight == null) {
            return "1.0";
        } else {
            return weight;
        }
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

}
